name: modbus-bridge
services:
    mqtt-bridge:
        image: torilabs/mqtt-prometheus-exporter:latest
        volumes:
            - ./mqtt2prometheus.yaml:/config.yaml
        networks:
            - monitoring
        depends_on:
            - mosquitto
        restart: unless-stopped

    mosquitto:
        image: eclipse-mosquitto:latest
        ports:
            - "1883:1883"
        networks:
            - monitoring
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
        restart: unless-stopped

    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus_data:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
            - "--web.enable-lifecycle"
        networks:
            - monitoring
        depends_on:
            - mqtt-bridge
        restart: unless-stopped

    grafana:
        image: grafana/grafana:latest
        volumes:
            - grafana_data:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
        ports:
            - "3333:3000"
            - "33333:3000"
        networks:
            - monitoring
        depends_on:
            - prometheus
        restart: unless-stopped

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
    monitoring:
        enable_ipv6: true
