services:
    traefik:
        image: traefik:v3
        ports:
            - "80:80"
            - "443:443"
            - "8081:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
            - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
            - traefik-acme:/etc/traefik/acme
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mosquitto:
        image: eclipse-mosquitto:latest
        ports:
            - "1883:1883"
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr:latest
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Prague
        extra_hosts:
            - "host.docker.internal:host-gateway"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.radarr.rule=Host(`radarr.naboo.lan`)"
            - "traefik.http.routers.radarr.entrypoints=web"
            - "traefik.http.routers.radarr.middlewares=ipwhitelist@file"
        volumes:
            - /opt/radarr:/config
            - /mnt/media/plex:/media
        ports:
            - 7878:7878
        restart: unless-stopped

    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.sonarr.rule=Host(`sonarr.naboo.lan`)"
            - "traefik.http.routers.sonarr.entrypoints=web"
            - "traefik.http.routers.sonarr.middlewares=ipwhitelist@file"
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Prague
        volumes:
            - /opt/sonarr:/config
            - /mnt/media/plex:/media
        ports:
            - 8989:8989
        restart: unless-stopped

    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.naboo.lan`)"
            - "traefik.http.routers.prowlarr.entrypoints=web"
            - "traefik.http.routers.prowlarr.middlewares=ipwhitelist@file"
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Prague
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - /opt/prowlarr:/config
        ports:
            - 9696:9696
        restart: unless-stopped

    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.bazarr.rule=Host(`bazarr.naboo.lan`)"
            - "traefik.http.routers.bazarr.entrypoints=web"
            - "traefik.http.routers.bazarr.middlewares=ipwhitelist@file"
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Prague
        volumes:
            - /opt/bazarr:/config
            - /mnt/media/plex:/media
        ports:
            - 6767:6767
        restart: unless-stopped

    overseerr:
        image: sctx/overseerr:latest
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.overseerr.rule=Host(`overseerr.naboo.lan`) || Host(`filmy.naboo.lan`) || Host(`movies.naboo.lan`)"
            - "traefik.http.routers.overseerr.entrypoints=web"
            - "traefik.http.routers.overseerr.middlewares=ipwhitelist@file"
        environment:
            - TZ=Europe/Prague
            - PORT=5055
        ports:
            - 5055:5055
        volumes:
            - /opt/overseerr:/app/config
        restart: unless-stopped

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.qbittorrent.rule=Host(`torrent.naboo.lan`)"
            - "traefik.http.routers.qbittorrent.entrypoints=web"
            - "traefik.http.routers.qbittorrent.middlewares=ipwhitelist@file"
            - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Prague
            - WEBUI_PORT=8080
            - TORRENTING_PORT=6881
        volumes:
            - /opt/qbittorrent:/config
            - /mnt/media/plex/torrentz:/downloads
        ports:
            - 8080:8080
            - 6881:6881
            - 6881:6881/udp
        restart: unless-stopped

volumes:
    traefik-acme:
