http:
    middlewares:
        ipwhitelist:
            ipWhiteList:
                sourceRange:
                    - "192.168.0.0/24"
    routers:
        homeassistant:
            rule: "Host(`ha.naboo.lan`) || Host(`ha.wmatex.cz`)"
            service: homeassistant
            entryPoints:
                - web
            middlewares:
                - ipwhitelist@file

        plex:
            rule: "Host(`plex.naboo.lan`)"
            service: plex
            entryPoints:
                - web
            middlewares:
                - ipwhitelist@file
    services:
        homeassistant:
            loadBalancer:
                servers:
                    - url: "http://192.168.10.10:8123"

        plex:
            loadBalancer:
                servers:
                    - url: "http://host.docker.internal:32400"
