http:
    middlewares:
        ipwhitelist:
            ipWhiteList:
                sourceRange:
                    - "192.168.0.0/24"
        redirect-to-https:
            redirectScheme:
                scheme: https
                permanent: true

    routers:
        homeassistant-lan:
            rule: "Host(`ha.naboo.lan`)"
            service: homeassistant
            entryPoints:
                - web
            middlewares:
                - ipwhitelist@file

        homeassistant-redirect:
            rule: "Host(`ha.wmatex.cz`)"
            service: homeassistant
            entryPoints:
                - web
            middlewares:
                - redirect-to-https@file

        homeassistant-tls:
            rule: "Host(`ha.wmatex.cz`)"
            service: homeassistant
            entryPoints:
                - websecure
            tls:
                certResolver: letsencrypt

        plex:
            rule: "Host(`plex.naboo.lan`)"
            service: plex
            entryPoints:
                - web
            middlewares:
                - ipwhitelist@file
    services:
        homeassistant:
            loadBalancer:
                servers:
                    - url: "http://192.168.10.10:8123"

        plex:
            loadBalancer:
                servers:
                    - url: "http://host.docker.internal:32400"
