http:
    routers:
        homeassistant:
            rule: "Host(`ha.naboo.lan`)"
            service: homeassistant
            entryPoints:
                - web

        plex:
            rule: "Host(`plex.naboo.lan`)"
            service: plex
            entryPoints:
                - web
    services:
        homeassistant:
            loadBalancer:
                servers:
                    - url: "http://192.168.10.10:8123"

        plex:
            loadBalancer:
                servers:
                    - url: "http://host.docker.internal:32400"
