http:
    routers:
        homeassistant:
            rule: "Host(`ha.naboo.lan`)"
            service: homeassistant
            entryPoints:
                - web
    services:
        homeassistant:
            loadBalancer:
                servers:
                    - url: "http://192.168.10.10:8123"
