entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"

api:
    dashboard: true
    insecure: true

providers:
    file:
        filename: /etc/traefik/dynamic.yml
        watch: true
    docker:
        exposedByDefault: false
