entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"
        transport:
            respondingTimeouts:
                readTimeout: 24h

api:
    dashboard: true
    insecure: true

certificatesResolvers:
    letsencrypt:
        acme:
            email: wmatex@gmail.com
            storage: /etc/traefik/acme/acme.json
            httpChallenge:
                entryPoint: web

providers:
    file:
        directory: /etc/traefik/conf.d
        watch: true
    docker:
        exposedByDefault: false
