http:
    routers:
        nextcloud:
            rule: "Host(`cloud.wmatex.cz`) | Host(`cloud.naboo.lan`)"
            entrypoints:
                - "https"
            service: nextcloud
            middlewares:
                - nextcloud-chain
            tls:
                certresolver: "letsencrypt"

    services:
        nextcloud:
            loadBalancer:
                servers:
                    - url: "http://host.docker.internal:11000" # Adjust to match APACHE_PORT and APACHE_IP_BINDING. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#adapting-the-sample-web-server-configurations-below

    middlewares:
        nextcloud-secure-headers:
            headers:
                hostsProxyHeaders:
                    - "X-Forwarded-Host"
                referrerPolicy: "same-origin"

        https-redirect:
            redirectscheme:
                scheme: https

        nextcloud-chain:
            chain:
                middlewares:
                    # - ... (e.g. rate limiting middleware)
                    - https-redirect
                    - nextcloud-secure-headers
